# Generated by Django 3.0.3 on 2020-03-01 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='xyz', max_length=25)),
                ('lastname', models.CharField(default='xyz', max_length=25)),
                ('contact', models.IntegerField(default='22507070707')),
                ('genre', models.CharField(choices=[('M', 'Male'), ('F', 'Femelle')], default='Male', max_length=25)),
                ('age', models.DateField(default=django.utils.timezone.now)),
                ('pays', django_countries.fields.CountryField(default="COTE D'IVOIRE", max_length=2)),
                ('ville', models.CharField(default='ABIDJAN', max_length=125)),
                ('emploi', models.CharField(default='INVENTEUR', max_length=125)),
                ('bio', models.TextField(default='Ma biographie...')),
                ('image', models.ImageField(default='default.jpg', upload_to='img_profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
